### ISSUE TITLE
Specification usage error

### ISSUE THREAD

**Issue by Andrea** [riteshrao/ncommon#2]
Hi there

I found a strange thing happening when using specification
If you run this test ( you can add it to the NHRepositoryTests.cs in namespace NCommon.Data.NHibernate.Tests) :

```
    [Test]
    public void Query_Using_OrderBy_In_Specification()
    {
        using (var testData = new NHTestDataGenerator(Factory.OpenSession()))
        using (new UnitOfWorkScope())
        {
            testData.Batch(actions =>
            {
                actions.CreateOrdersForCustomers(actions.CreateCustomersInState("PA", 2));
                actions.CreateOrdersForCustomers(actions.CreateCustomersInState("DE", 5));
                actions.CreateOrdersForCustomers(actions.CreateCustomersInState("LA", 3));
            });

            var customersInPA = new Specification<Order>(x => string.Compare( x.Customer.Address.State , "PA")==0);
            var ordersRepository = new NHRepository<Order>();
            var results = from order in ordersRepository.Query(customersInPA)
                          orderby order.OrderDate
                          select order;

            Assert.That(results.Count() > 0);
            Assert.That(results.Count(), Is.EqualTo(2));
        }
    }
```

The test fails with a QueryException
 NHibernate.QueryException: Cannot use subqueries on a criteria without a projection.
However, all works fine if you try this

```
    [Test]
    public void Query_Using_Specification()
    {
        using (var testData = new NHTestDataGenerator(Factory.OpenSession()))
        using (new UnitOfWorkScope())
        {
            testData.Batch(actions =>
            {
                actions.CreateOrdersForCustomers(actions.CreateCustomersInState("PA", 2));
                actions.CreateOrdersForCustomers(actions.CreateCustomersInState("DE", 5));
                actions.CreateOrdersForCustomers(actions.CreateCustomersInState("LA", 3));
            });

            var customersInPA = new Specification<Order>(x => string.Compare( x.Customer.Address.State , "PA", StringComparison.OrdinalIgnoreCase)==0);
            var ordersRepository = new NHRepository<Order>();

            Assert.DoesNotThrow(() => ordersRepository.Query(customersInPA).OrderBy(x=>x.OrderDate));

        }
    }
```

The key here seems to be doing things with a Query() 

**Note: I just re ran the test and the passing test means nothing, as , as soon as you want to do anything with the collection it throws

Otherwise The library is great
I ll update if I find a solution to this
Thanks

**Comment by riteshrao** [comment]
This fails because of how the underlying criteria is being added by NHibernate.Linq to the query. Since you are using a string.Compare method for string comparison, NHibernate.Linq attempts to convert that to a criteria expression that would eventually be converted to SQL, but there is no conversion defined for string.Compare. So it attempts to add a projection to have the query evaluated after results have been returned from the database, but that wont work because it doesn't set a projection for the sub-query. 

Can I ask why use string.Compare? This would work if the spec is defined as:

new Specification<Order>(x => x.Customer.Address.State == "PA"); 

If your using Oracle, then I guess you'd need case insensitive comparison, otherwise SQL should do case insensitive string matching by default (unless the default collation is changed to a case-sensitive collation).

**Comment by Andrea** [comment]
HI there:
Thanks for the swift response, apologies, I forgot I d had comparison in a case insensitive manner by default,I wonder if this would this still hold in internationalised strings, however that is less of a pressing issue at the moment
Thanks again
