### ISSUE TITLE
Changes from earlier version

### ISSUE THREAD

**Issue by banico** [riteshrao/ncommon#8]
Hi. I would like to upgrade to the latest version of NCommon. However, I noticed some changes and I would like to ask if you can help by pointing me out to articles / forums where this has been addressed.
1. What happened to the Store container class?
2. What happened to the NHRepository constructor that accepts ISession?

If they're both gone, can you suggest what I should do in place of these?

Thanks very much.

**Comment by banico** [comment]
I also raised this in StackOverflow just in case someone in the community can address these. http://stackoverflow.com/questions/2918949/ncommon-changes-in-1-1

**Comment by banico** [comment]
Please ignore this thread. I just read http://www.codeinsanity.com/2010/04/refactoring-storage-in-ncommon-11.html

**Comment by riteshrao** [comment]
The Store container class is gone (although I've been debating with myself if I should add it back for backward compat... ) Use IState and other related interfaces in 1.1

As for NHRepository constructor that accepts ISession... that's been removed as well and won't be coming back. The constructor didn't make any sense, since you could just as easily setup ISession to use Linq, e.g. 

var query = from customer in session.Linq<Customer>() select customer

Instantiating a NHRepository in that case doesn't make sense, since NHRepository provides no additional value over using the Linq<> extension.

**Comment by riteshrao** [comment]
Closing this issue.
